# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'loterias' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for loterias
  pod 'Google-Mobile-Ads-SDK'

  #pod 'RNI18n', :path => '../node_modules/react-native-i18n'

  #pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  #pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  # pod 'RNSVG', :path => '../node_modules/react-native-svg'

end